@port = 8000

# Busca todos os usuários
GET http://localhost:{{port}}/api/usuario
Content-Type: application/json



###
# Busca todos os usuários ativos
GET http://localhost:{{port}}/api/usuario?ativo=true
Content-Type: application/json

###
# Busca todos os usuários inativos
GET http://localhost:{{port}}/api/usuario?ativo=false
Content-Type: application/json